INSERT INTO privileges(privilege) VALUES('User');
INSERT INTO privileges(privilege) VALUES('Moderator');
INSERT INTO privileges(privilege) VALUES('Admin');

INSERT INTO categories_products (name, description) VALUES ("Galleta", "Galletas de diferentes sabores e ingredientes");
INSERT INTO categories_products (name, description) VALUES ("Brownie", "Brownies de diferentes sabores e ingredientes");
INSERT INTO categories_products (name, description) VALUES ("Pastel", "Pasteles de diferentes sabores e ingredientes");
INSERT INTO categories_products (name, description) VALUES ("Otros", "Galletas para mascotas");

INSERT INTO categories_posts (name, description) VALUES ("Alimentación", "Post relacionados con la buena alimentación de los perros");
INSERT INTO categories_posts (name, description) VALUES ("Cuidado", "Post relacionados con el cuidado de los perros");
INSERT INTO categories_posts (name, description) VALUES ("Recetas", "Post relacionados con recetas de cocina para tu perro");
INSERT INTO categories_posts (name, description) VALUES ("Tips", "Post relacionados con tips para perros");

INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Carlos","Chongo","961-271-4616","cacc.chongo@gmail.com","patitas1207","2000-12-07",true,2);
INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Erik","Contreras","553-324-0297","casiqbp@gmail.com","patitas0806","2000-08-06",true,3);
INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Frida","Estrada","556-076-2559","FridaEstrada24@gmail.com","patitas0701","2001-07-01",true,2);
INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Victor","Mairena","558-826-6900","vmairenafx@gmail.com","patitas1117","1999-11-17",true,2);
INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Andres","Pardo","554-540-8030","jorgeandres.pardorea@gmail.com","patitas1126","1998-11-26",true,2);
INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Fernando","Cervantes","331-416-6668","fer2311cervantes@gmail.com","patitas1123","2000-11-23",true,2);
INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Giss","Islas","556-147-8199","gissislas0493@gmail.com","patitas0419","2000-04-19",true,2);
INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Daniela","Gomez","722-413-4818","dansmc.courses@gmail.com","patitas1218","2000-12-18",true,2);
INSERT INTO users(first_name,last_name,telephone_number,email,password,birth_date,is_active,id_privilege) VALUES("Bastian","Cortés","332-493-0455","coab1998@gmail.com","patitas1002","2000-10-02",true,2);

INSERT INTO reviews(content, rating, date, validation, id_user) VALUES("¡Increíble sabor y presentación impecable! Nunca me decepcionan, son mi tienda favorita.", 5, "2024-03-03", 1, 1);
INSERT INTO reviews(content, rating, date, validation, id_user) VALUES("Los postres de este ecommerce son una verdadera obra de arte. ¡Cada bocado es exquisito!", 5, "2024-03-22", 1, 2);
INSERT INTO reviews(content, rating, date, validation, id_user) VALUES("¡La calidad de los ingredientes se nota en cada postre! ¡Nunca me canso de ordenar aquí!", 5, "2024-04-09", 1, 3);
INSERT INTO reviews(content, rating, date, validation, id_user) VALUES("¡Los postres son una explosión de sabores! Siempre alegran mis reuniones familiares.", 5, "2024-04-13", 1, 4);
INSERT INTO reviews(content, rating, date, validation, id_user) VALUES("¡Estoy enamorado de estos postres! Siempre llegan en perfecto estado ,son perfectos para cualquier comida.", 5, "2024-04-16", 1, 5);

INSERT INTO posts (title, description,content,date, id_user, id_category_post) VALUES("La influencia de las mascotas en la vida humana", "La influencia positiva de las mascotas en la salud y bienestar humanos", "La influencia positiva de las mascotas en la salud y bienestar humanos es ampliamente reconocida, abarcando aspectos psicológicos, fisiológicos, terapéuticos y socioemocionales. Su papel como facilitadores en terapias motivacionales y físicas para diversas enfermedades ha permitido la aplicación de los efectos beneficiosos de tener mascotas en contextos terapéuticos.\n\nAdemás, la presencia de mascotas se ha identificado como un factor protector contra enfermedades cardiovasculares y como un medio para reducir el estrés en sus dueños, brindando apoyo emocional, mitigando la sensación de soledad y fomentando la interacción social.","2024-02-14",2,4);
INSERT INTO posts (title, description,content,date, id_user, id_category_post) VALUES("Cuidados que debes conocer", "Conoce los principales cuidados para tus mascotas","Cuidar a un perro implica compromiso y atención. En general, es importante procurar una alimentación saludable para ellos, así como favorecer su actividad física y estimular su socialización. También es fundamental ofrecerle cuidados y revisiones veterinarias para controlar su estado de salud y mejorar su calidad de vida.\n\nSi se trata de un cachorro recién nacido, los cuidados del perro serán continuos, incluyendo el amamantamiento con leche materna o sustitutivo, y el destete, que se inicia a partir de las cuatro semanas de vida y de forma progresiva.\n\nMientras que, si se trata de un perro de edad más avanzada que adoptamos en casa, hay algunas indicaciones a tener en cuenta, como darle mucho cariño, seguridad y comprensión. Y en este caso, lo mejor es sacarle en paseos cortos y frecuentes para que se vaya habituando poco a poco a su nueva rutina fuera de la protectora o refugio.\n\nEs muy importante tomar conciencia de que tener una mascota implica una gran dedicación y responsabilidad. Cuando decidimos acoger a un perro en casa debemos estar dispuestos a cubrir todas sus necesidades. Esta animal requiere compromiso, mimo y tiempo. No solo se trata de abastecerle de agua y comida, sino que hay mucho más.\n\nEsos son los principales cuidados del perro que debes conocer y aplicar para favorecer su salud.\n\nAlimentación de calidad\nElegir un pienso nutritivo y darles una buena hidratación es clave para el bienestar de los perros. Hay que ofrecerles alimentos de calidad en función de su etapa de vida, según si es cachorro, adulto o senior.\n\nSi se trata de un cachorro o de un perro mayor habrá que adaptar su dieta a sus requerimientos. Lo mismo sucede si la mascota tiene alguna intolerancia, patología o necesidad alimentaria específica.\n\nEducación animal\nEnseñar a un perro es esencial para que se desarrolle satisfactoriamente. Hay que indicarle dónde hacer sus necesidades, en qué espacios, qué puede hacer y que no, y guiarlo desde el principio para inculcarle un buen aprendizaje. Eso sí, siempre desde el refuerzo positivo, evitando reñirle bruscamente o gritarle, ya que así solo conseguiremos asustarle.\n\nPor otra parte, la educación canina también implica la interacción del perro con su entorno. Nos referimos a socializarle tanto con otras personas, como con otros canes. Y en el caso de que muestre una conducta de miedo, desconfianza o de agresividad, es aconsejable consultar con un adiestrador canino para reconducir su conducta.", "2024-03-20",2,4);
INSERT INTO posts (title, description,content,date, id_user, id_category_post) VALUES("Sabías que… ?", "Los perros son nuestros amigos inseparables y por ello siempre queremos compartirles de nuestros gustos", "Los perros son nuestros amigos inseparables y por ello siempre queremos compartirles de nuestros gustos, si bien muchas cosas que les damos les pueden gustar mucho no todo les es bueno para su salud, hay algunos alimentos que son nocivos para su salud aquí te dejamos una pequeña lista.\n\n- Chocolate. No metabolizan las metilxantinas, por lo que resulta muy tóxico para ellos.\n\n- Caramelos Causan vómitos y bajada súbita de la glucosa en sangre.\n\n- Cebollas, ajos, puerros y similares. Ni crudos ni cocinados. Causan anemia por hemólisis (destrucción de los glóbulos rojos).\n\n- Uvas y pasas. Son nefrotóxicas, es decir, causan fallo renal.\n\n- Aguacate. Este fruto contiene una toxina fungicida llamada persina, tras su consumo puede haber síntomas leves, como diarrea y vómitos, pero en casos más graves llega a ocasionar pancreatitis.\n\n- Frutos secos. Las más peligrosas son las nueces de macadamia, cuyo consumo puede ocasionar un cuadro de debilidad, temblores y vómitos. También las almendras, que en grandes cantidades pueden causar pancreatitis.", "2024-04-19",2,4);

INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Galleta de Chocolate", "Terrier de Chocolate", "Galleta de chocolate con relleno de chocolate", 35, 1, "https://raw.githubusercontent.com/Alera9/product-img/main/Galleta-chocolate.png", 1);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Galleta de Mantequilla", "Corgi Cookies", "Galleta de mantequilla suave con forma de Corgi" , 120, 6, "https://raw.githubusercontent.com/Alera9/product-img/main/galleta-mantequilla.png", 1);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Galleta de Avena", "Poodle Oat Puffs",  "Galleta de avena bañadas en azucar glass", 35, 9, "https://raw.githubusercontent.com/Alera9/product-img/main/Galleta-avena.png", 1);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Galleta de Chispas", "Dalmata Delight",  "Galleta de mantequilla con chispas de chocolate", 35, 7, "https://raw.githubusercontent.com/Alera9/product-img/main/galleta-chispas.png", 1);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Brownie de Chocolate", "Labrabownie",  "Pastelillo de chocolate con relleno de chocolate", 50, 10, "https://raw.githubusercontent.com/Alera9/product-img/main/brownie-chocolate.png", 2);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Brownie de Frambuesa", "Pastorcito de Frambuesa", "Pastelillo de chocolate con decoracion de frambuesa" , 50, 10,"https://raw.githubusercontent.com/Alera9/product-img/main/brownie-frambuesa.png", 2);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Pastel de Tres Leches", "Husky de 3 Leches",  "Pastel de Tres Leches", 50, 7,"https://raw.githubusercontent.com/Alera9/product-img/main/pastel-de-tres-leches.png", 3);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Pastel de Chocolate", "Chocolate Retriever",  "Pastel de chocolate con cubierta de chocolate", 50, 10,"https://raw.githubusercontent.com/Alera9/product-img/main/pastel-de-chocolate.png", 3);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Pastel de Zanahoria", "Pug de zanahoria /carrot bite",  "Pastel de zanahoria con betún de queso crema", 50, 10,"https://raw.githubusercontent.com/Alera9/product-img/main/pastel-de-zanahoria.png", 3);
INSERT INTO products (name, dogo_name, description, price, quantity, image_URL, id_category_product) VALUES ("Pastel Cheesecake", "Cheehuhua Dream",  "Pastel de cheesecake con decoracion de chocolate", 50, 10,"https://raw.githubusercontent.com/Alera9/product-img/main/pastel-cheescake.png", 3);
